# Generated by Django 2.0.6 on 2018-06-29 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('change_status', 'Can change status'),)},
        ),
    ]
