# Generated by Django 2.0.6 on 2018-07-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180706_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
