# Generated by Django 2.0.6 on 2018-07-06 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20180706_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator('^\\+380\\d{9}$', "Phone number must be entered in the format: '+380xxxxxxxxx'.")]),
        ),
    ]
